export enum SpeakerStyle {
  advertisement_upbeat = "advertisement_upbeat",
  affectionate = "affectionate",
  angry = "angry",
  assistant = "assistant",
  calm = "calm",
  chat = "chat",
  cheerful = "cheerful",
  customerservice = "customerservice",
  depressed = "depressed",
  disgruntled = "disgruntled",
  "documentary-narration" = "documentary-narration",
  embarrassed = "embarrassed",
  empathetic = "empathetic",
  envious = "envious",
  excited = "excited",
  fearful = "fearful",
  friendly = "friendly",
  gentle = "gentle",
  hopeful = "hopeful",
  lyrical = "lyrical",
  "narration-professional" = "narration-professional",
  "narration-relaxed" = "narration-relaxed",
  newscast = "newscast",
  "newscast-casual" = "newscast-casual",
  "newscast-formal" = "newscast-formal",
  "poetry-reading" = "poetry-reading",
  sad = "sad",
  serious = "serious",
  shouting = "shouting",
  sports_commentary = "sports_commentary",
  sports_commentary_excited = "sports_commentary_excited",
  whispering = "whispering",
  terrified = "terrified",
  unfriendly = "unfriendly",
}

// https://learn.microsoft.com/en-us/azure/ai-services/speech-service/speech-synthesis-markup-voice
