name: "CI"
on:
  pull_request:
    branches:
      - "**"
      - "!main"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: action-setup@v2
        with:
          version: 6.0.2
      - run: npm i
  install:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: action-setup@v2
        with:
          version: 6.0.2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm i
